### ISSUE TITLE
Installlation disables already installed NGINX 

### ISSUE THREAD

**Issue by derneuere** [LibrePhotos/librephotos-linux#13]
From Discord:

LibrePhotos disables already valid nginx configurations and installations, because
This line in the installation script disables nginx to listen port 443, because it overwrites old nginx configurations:
https://github.com/LibrePhotos/librephotos-linux/blob/288b619d1cc34bfc4b094d32ff2ad8bec894808e/install-librephotos.sh#L57

The user said it must be something like this:
```
cp ressources/etc/nginx/nginx.conf /etc/nginx/sites-available/librephotos
ln -s /etc/nginx/sites-available/librephotos /etc/nginx/sites-enabled
```

**Comment by Seneliux** [comment]
In Ubuntu the path /etc/nginx/sites-available/ is default virtual hosts directory. /etc/nginx/nginx.conf is config of nginx itself.

This problem occurs if nginx is already installed - script overwrites good nginx config, and not adding virtual host.
Possible solution:
check nginx, if not installed, then:
`cp ressources/etc/nginx/nginx.conf /etc/nginx/nginx.conf `
if installed:
`
cp ressources/etc/nginx/libprehotos /etc/nginx/sites-available/librephotos
ln -s /etc/nginx/sites-available/librephotos /etc/nginx/sites-enabled
`
Contents of the ressources/etc/nginx/libprehotos (subdomain!):
```
server {
        server_name librephotos.example.com;
        error_log /var/log/nginx/librephotos.error warn;

 location ~ ^/(api|media)/ {
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header Host backend;
      include uwsgi_params;
      #issue with IPV6 on ubuntu 20.04
      #unicorn need to listen on [::1]
      proxy_pass http://127.0.0.1:8001;
    }
    # Django media
    location /protected_media  {
        internal;
        alias /var/lib/librephotos/protected_media/;
    }
    # Original Photos
    location /original  {
        internal;
        alias /var/lib/librephotos/data/;
    }
    # Nextcloud Original Photos
    location /nextcloud_original  {
        internal;
        alias /var/lib/librephotos/nextcloud_media/;
    }

```
