### ISSUE TITLE
spacy module installation error

### ISSUE THREAD

**Issue by atlynceus** [LibrePhotos/librephotos-linux#14]
On Debian 10.9 python module spacy can't be installed without prior installation of  setuptools and wheel.

**Comment by imval** [comment]
I solved the issue by installing the package python3-setuptools on my Debian 10 LXC Instance. Thanks for the hint.

**Comment by imval** [comment]
It should probably be installed by the script.

**Comment by tomamplius** [comment]
I did test a long time ago, but I believe that in Debian 10 have Python3.7 by default but  librephoto need Python3.8 or greatess version.
I 'm wrong? 
But i have test today and spacy issue is on debian 11 too.

src : https://packages.debian.org/buster/python3

**Comment by timdonovanuk** [comment]
Same issue, the install instructions don't work. After installing python3-setuptools I still get spacy error. I tried installing it manually but that failed too but get `Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-za6nezx3/blis/`

**Comment by timdonovanuk** [comment]
Seems like:

```
sudo python3 -m pip install --upgrade pip
sudo python3 -m pip install --upgrade setuptools
```

then running` ./install-librephotos.sh `again worked

**Comment by derneuere** [comment]
Spacy is no longer used.
