### ISSUE TITLE
Can not create new face ID

### ISSUE THREAD

**Issue by Seneliux** [LibrePhotos/librephotos-linux#37]
In the Face recognition dashboard.
After  pushing green button "Add to existing face ID or create a new face ID" getting white page. No opening face id creation dialog.
Firefox, Chrome.
Other buttons "Delete the face and its thumbnails", "Train a classifier and automatically label faces" works fine.

**Comment by derneuere** [comment]
I fixed that on commit: https://github.com/LibrePhotos/librephotos-frontend/commit/12b145458aca5c320c9d34728884e87979d4c583

I think doing a git pull and building the frontend should do the trick :)
