### ISSUE TITLE
No faces showing in faces dashboard

### ISSUE THREAD

**Issue by bstyx09** [LibrePhotos/librephotos-linux#38]
The folder on the drive shows that it did scan some faces so it seems like the scan process worked, but navigating to the faces page returns a 404 and a 500 level error.

![image](https://user-images.githubusercontent.com/6361999/151477350-be85b360-f19e-47b1-9adf-b74464d39555.png)

all of the logs I've found seem fine and don't have any indication that something isn't working. I'm not really sure what else to look for.

The face cluster page is also returning a 500 error too:
![image](https://user-images.githubusercontent.com/6361999/151477702-7b2af3ef-d890-4f48-a640-b1ec04ca5541.png)

**Comment by Seneliux** [comment]
Have you checked nginx logs? I guess that this problem caused by reverse proxy. 500 and 404 errors are releated to web server.

**Comment by bstyx09** [comment]
I do see the requests with the response codes in the access log file, but unfortunately no details listed in the error log file. The error log doesn't show any data when the failing requests come through.

![image](https://user-images.githubusercontent.com/6361999/151574826-e0419440-3feb-4921-8a82-254148308695.png)

I am hitting the host directly to access the UI for the moment so there shouldn't be anything in front of nginx that could be causing this

**Comment by Seneliux** [comment]
Hmm, looks works fine. Maybe try:
as root:
1. /usr/lib/librephotos/bin/librephotos-upgrade
www:
2. rescan faces / train faces (may be forgot :D ) in the library dashboard, not in the faces
3. look at the admin area - is training face succesfull?

**Comment by bstyx09** [comment]
Went ahead and ran the upgrade command, then also rescanned the filesystem, rescanned faces, and then had it train faces.
In the admin area I see that scanning faces failed when I tried to run it, but the train faces job was able to train 2 of them according to that page:

![image](https://user-images.githubusercontent.com/6361999/151585185-3b4ea975-f4f8-4f53-9c83-53f16d2ca525.png)

There are 398 faces in the "/var/lib/librephotos/protected_media/faces" directory so it seems like it's seeing them but just not able to pull them out for whatever reason. The face recognition page still shows no faces.

I was able to see some errors in the ownphotos.log file:
![image](https://user-images.githubusercontent.com/6361999/151584914-c2753db3-2dab-4023-be67-65c47a755b4c.png)

**Comment by Seneliux** [comment]
Please check the folders / files  permissions:
ls -l /librephotos/folder/
and deeper like /librephotos/folder/{data,protected_media}
Owner must be librephotos. And mode 755. 
I personally changed the owner:group to librephotos:ME and mode 775.
Or simply run (change LIBREPHOTOS to correct path):
chown -R librephotos:librephotos /LIBREPHOTOS
chmod -R 755 /LIBREPHOTOS

**Comment by bstyx09** [comment]
That did it! For whatever reason I assumed it used www-data user account instead of one specific to librephotos.

Thanks a ton, it's working pretty well so far!
