### ISSUE TITLE
syntax error configuring database "CREATE USER docker"

### ISSUE THREAD

**Issue by denkab** [LibrePhotos/librephotos-linux#52]
Installing on Ubuntu 20.04.5 LTS with all defaults results in the following error:

```
Synchronizing state of postgresql.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable postgresql
+ su - postgres
NOTICE:  database "librephotos" does not exist, skipping
DROP DATABASE
NOTICE:  role "librephotos" does not exist, skipping
DROP ROLE
ERROR:  syntax error at or near "AaAa1234"
LINE 1: CREATE USER docker with encrypted password AaAa1234;
                                                   ^
ERROR:  role "librephotos" does not exist
ERROR:  database "librephotos" does not exist
```

**Comment by denkab** [comment]
reverting changes in https://github.com/LibrePhotos/librephotos-linux/commit/ce8353bb8cd12f24fe1e1223f48382709293ce1d locally allows the script to proceed

**Comment by denkab** [comment]
I don't understand postgresql enough, so it is confusing to me that the script tries to create a database owned by a user on line 80 that has been dropped on line 78

**Comment by Nerodacles** [comment]
> I don't understand postgresql enough, so it is confusing to me that the script tries to create a database on line 80 owned by a user that has been dropped on line 78

Because for the fresh install script, it needs a "new" account and table, or at least one that is blank.
