### ISSUE TITLE
mixup pgsql users

### ISSUE THREAD

**Issue by rincewind0803** [LibrePhotos/librephotos-linux#54]
in [https://github.com/LibrePhotos/librephotos-linux/pull/53](url) we drop user libreprotos
Crate user docker >>> should be librephotos
and try to assign db to user librephotos
That is imho the real issue in [https://github.com/LibrePhotos/librephotos-linux/pull/52](url)

**Comment by c0bnut** [comment]
I can confirm after changing the user docker to librephotos the script continues, however I do get other errors regarding python later in the script.
The commit which broke this is [c7be102](https://github.com/LibrePhotos/librephotos-linux/commit/c7be1028cb5478ad49ec87731c11c8c745d2eb3c)

**Comment by derneuere** [comment]
The goal is it to make the setup for the local install and the docker all in one image more similar.
The docker image uses a user named "docker" for postgres. I wanted to make this one the default.

Can you help me find out which lines I have to change for that?

**Comment by rincewind0803** [comment]
That kind of explains whats happenig here, tater on the script fails again  at this Line
`if [[ -z "${DOCKERDEPLOY}" ]]; then
    rm /tmp/database_pass
else
  echo "skipping temp database pass removal"
fi
`
Though i'm  not doing a dockerdeploy it enters the if and tries to remove the  /tmp/database_pass and errors out
My guess is that its not correctly getting if local install or dockerdeploy.

I will look into it tonight.

**Comment by cahaya42** [comment]
I cannot find any evidence that the script creates /tmp/database_pass file.
I suggest the safest change is to update
`if [[ -z "${DOCKERDEPLOY}" ]];`
to include a test for file existence before removing the file
`if [[ -z "${DOCKERDEPLOY}" && -f /tmp/database_pass ]]; then`

**Comment by cahaya42** [comment]
I found in `/etc/librephotos/librephotos-backend.env` that DB_USER was set to docker.
The source for this file appears to [`resources/etc/librephotos/librephotos-backend.env`](https://github.com/LibrePhotos/librephotos-linux/blob/main/resources/etc/librephotos/librephotos-backend.env#L13), which was not changed as part of the [c7be102](https://github.com/LibrePhotos/librephotos-linux/commit/c7be1028cb5478ad49ec87731c11c8c745d2eb3c) edit of `install-librephotos.sh`.
